name: Release

on:
  push:
    branches:
      - 'DISABLED--main--'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: |
        npm install
    - name: Run QA
      run: |
        npm run qa
    - name: Compile TypeScript
      run: |
        npm run build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_MH }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_MH }}
      run: npx semantic-release